// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/universe/claude-monitor/internal/server (interfaces: SessionScanner)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_scanner.go -package=mocks github.com/universe/claude-monitor/internal/server SessionScanner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/universe/claude-monitor/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionScanner is a mock of SessionScanner interface.
type MockSessionScanner struct {
	ctrl     *gomock.Controller
	recorder *MockSessionScannerMockRecorder
	isgomock struct{}
}

// MockSessionScannerMockRecorder is the mock recorder for MockSessionScanner.
type MockSessionScannerMockRecorder struct {
	mock *MockSessionScanner
}

// NewMockSessionScanner creates a new mock instance.
func NewMockSessionScanner(ctrl *gomock.Controller) *MockSessionScanner {
	mock := &MockSessionScanner{ctrl: ctrl}
	mock.recorder = &MockSessionScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionScanner) EXPECT() *MockSessionScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockSessionScanner) Scan(ctx context.Context) ([]model.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx)
	ret0, _ := ret[0].([]model.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockSessionScannerMockRecorder) Scan(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockSessionScanner)(nil).Scan), ctx)
}
